FROM ghcr.io/cirruslabs/flutter:3.29.3 as builder

WORKDIR /app

RUN flutter config --enable-web

COPY . /app

RUN flutter clean
RUN flutter pub get

RUN flutter build web -t lib/main_dohomeuat.dart --dart-define=ENVIRONMENT=DOHOME_UAT --dart-define=FLAVOR=dohomeuat

FROM nginx:1.25-alpine-slim

ADD nginx_conf/nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/build/web /usr/share/nginx/html
EXPOSE 80