// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
    appId: 'REPLACE_WITH_YOUR_FIREBASE_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_FIREBASE_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_FIREBASE_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_FIREBASE_STORAGE_BUCKET',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
    appId: 'REPLACE_WITH_YOUR_FIREBASE_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_FIREBASE_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_FIREBASE_PROJECT_ID',
    authDomain: 'REPLACE_WITH_YOUR_FIREBASE_AUTH_DOMAIN',
    storageBucket: 'REPLACE_WITH_YOUR_FIREBASE_STORAGE_BUCKET',
    measurementId: 'REPLACE_WITH_YOUR_FIREBASE_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
    appId: 'REPLACE_WITH_YOUR_FIREBASE_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_FIREBASE_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_FIREBASE_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_FIREBASE_STORAGE_BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
    appId: 'REPLACE_WITH_YOUR_FIREBASE_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_FIREBASE_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_FIREBASE_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_FIREBASE_STORAGE_BUCKET',
    androidClientId: 'REPLACE_WITH_YOUR_FIREBASE_ANDROID_CLIENT_ID',
    iosClientId: 'REPLACE_WITH_YOUR_FIREBASE_IOS_CLIENT_ID',
    iosBundleId: 'com.dede.merchant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
    appId: 'REPLACE_WITH_YOUR_FIREBASE_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_FIREBASE_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_FIREBASE_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_FIREBASE_STORAGE_BUCKET',
    androidClientId: 'REPLACE_WITH_YOUR_FIREBASE_ANDROID_CLIENT_ID',
    iosClientId: 'REPLACE_WITH_YOUR_FIREBASE_IOS_CLIENT_ID',
    iosBundleId: 'smlaicloud.smlaicloud',
  );
}
