name: tigerboard
description: Dart package which manages the tigerboard payment domain.
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  json_annotation: any
  decimal: any
  dio: any
  intl: any
  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Your other dev_dependencies here
  build_runner: any
  json_serializable: any