name: gbprimepay
description: Dart package which manages the gbprimepay payment domain.
publish_to: none

environment:
  sdk: ^3.5.4


dependencies:
  json_annotation: any
  decimal: any
  dio: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Your other dev_dependencies here
  build_runner: any
  json_serializable: any