// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }

//     // Check flavor from compile-time constant
//     const flavor = String.fromEnvironment('FLAVOR', defaultValue: 'dedekiosk');

//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return flavor == 'bckiosk' ? androidBckiosk : androidDedekiosk;
//       case TargetPlatform.iOS:
//         return flavor == 'bckiosk' ? iosBckiosk : iosDedekiosk;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   // Legacy aliases for backward compatibility
//   static FirebaseOptions get android => androidDedekiosk;
//   static FirebaseOptions get ios => iosDedekiosk;

//   // DeDe Kiosk Firebase Options
//   static const FirebaseOptions androidDedekiosk = FirebaseOptions(
//     apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
//     appId: 'REPLACE_WITH_YOUR_FIREBASE_APP_ID',
//     messagingSenderId: 'REPLACE_WITH_YOUR_FIREBASE_SENDER_ID',
//     projectId: 'REPLACE_WITH_YOUR_FIREBASE_PROJECT_ID',
//     storageBucket: 'REPLACE_WITH_YOUR_FIREBASE_STORAGE_BUCKET',
//   );

//   static const FirebaseOptions iosDedekiosk = FirebaseOptions(
//     apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
//     appId: 'REPLACE_WITH_YOUR_FIREBASE_APP_ID',
//     messagingSenderId: 'REPLACE_WITH_YOUR_FIREBASE_SENDER_ID',
//     projectId: 'REPLACE_WITH_YOUR_FIREBASE_PROJECT_ID',
//     storageBucket: 'REPLACE_WITH_YOUR_FIREBASE_STORAGE_BUCKET',
//     androidClientId: 'REPLACE_WITH_YOUR_FIREBASE_ANDROID_CLIENT_ID',
//     iosClientId: 'REPLACE_WITH_YOUR_FIREBASE_IOS_CLIENT_ID',
//     iosBundleId: 'com.smlsoft.dedekiosk',
//   );

//   // BC Kiosk Firebase Options
//   static const FirebaseOptions androidBckiosk = FirebaseOptions(
//     apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
//     appId: 'REPLACE_WITH_YOUR_FIREBASE_APP_ID',
//     messagingSenderId: 'REPLACE_WITH_YOUR_FIREBASE_SENDER_ID',
//     projectId: 'REPLACE_WITH_YOUR_FIREBASE_PROJECT_ID',
//     storageBucket: 'REPLACE_WITH_YOUR_FIREBASE_STORAGE_BUCKET',
//   );

//   static const FirebaseOptions iosBckiosk = FirebaseOptions(
//     apiKey: 'REPLACE_WITH_YOUR_FIREBASE_API_KEY',
//     appId: 'REPLACE_WITH_YOUR_FIREBASE_APP_ID', // TODO: Update with actual bckiosk iOS app ID when created
//     messagingSenderId: 'REPLACE_WITH_YOUR_FIREBASE_SENDER_ID',
//     projectId: 'REPLACE_WITH_YOUR_FIREBASE_PROJECT_ID',
//     storageBucket: 'REPLACE_WITH_YOUR_FIREBASE_STORAGE_BUCKET',
//     androidClientId: 'REPLACE_WITH_YOUR_FIREBASE_ANDROID_CLIENT_ID',
//     iosClientId: 'REPLACE_WITH_YOUR_FIREBASE_IOS_CLIENT_ID',
//     iosBundleId: 'com.smlsoft.bckiosk',
//   );
// }
